version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - export _DOCKER_REPO="$(aws ecr get-authorization-token --output text  --query 'authorizationData[].proxyEndpoint')"
      - aws ecr get-login --no-include-email --region ca-central-1 | awk '{print $6}' | docker login -u AWS --password-stdin $_DOCKER_REPO
      - npm i npm@latest -g
      - pip install --upgrade pip
      - pip install --upgrade awscli
  pre_build:
    commands:
      - npm install
      - npm test
  build:
    commands:
      - docker build -t xerp_client .
      - docker tag xerp_client:latest 825035741702.dkr.ecr.ca-central-1.amazonaws.com/xerp_client:latest
  post_build:
    commands:
      - docker push 825035741702.dkr.ecr.ca-central-1.amazonaws.com/xerp_client:latest
